config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/About'

  get 'pages/Contact'

  get 'pages/Projects'

  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def About
  end

  def Contact
  end

  def Projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phrasing_helper.rb
module PhrasingHelper
  # You must implement the can_edit_phrases? method.
  # Example:
  #
  # def can_edit_phrases?
  #  current_user.is_admin?
  # end

  def can_edit_phrases?
    current_user
   end
end

app/views/articles/_form.html.erb
<div class="row justify-content-center">
  <div class="col-lg-10">
    <h3>New Article</h3>
    <form>
    <div class="form-group">
    <%= simple_form_for(article) do |f| %>
      <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

        <%= f.input :title, placeholder: 'title', label: false %>
        <%= f.input :content, placeholder: 'content', label: false %>
        <%= f.button :submit %>

    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row justify-content-center">
    <% @articles.reverse.each do |article| %>
    <div class="col-8">
      <br>
      <h2><%= article.title %></h2>
      <p class="time_ago">Posted <%= time_ago_in_words(article.created_at) %> ago</p>
      <p><%= article.content %></p>
      <% if user_signed_in? %>
      <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-secondary btn-sm"><%= link_to 'Show', article %></button>
        <button type="button" class="btn btn-secondary btn-sm"><%= link_to 'Edit', edit_article_path(article) %></button>
        <button type="button" class="btn btn-secondary btn-sm"><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        <% else %>
        <% end %>
      </div>
    </div>
    <% end %>
</div>  
  

<div><%= link_to 'New Article', new_article_path, class: "btn btn-primary btn-sm" %></div>

app/views/articles/new.html.erb
<p id="notice"><%= notice %></p>
<br><br><br>
<div class="flex-lg-row">
	<%= render 'form', article: @article %>

	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">
  <%= @article.title %>
</h1>

<p>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_header.html.erb
    <!-- Page Header -->
    <header class="masthead">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
                    <div class="site-heading">
                        <h1>Tech, Digital, Startups</h1>
                        <span class="subheading">Just another weblog</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

app/views/layouts/_navbar.html.erb
    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-toggleable-md navbar-light" id="mainNav">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
               <i class="fa fa-bars" aria-hidden="true"></i>
            </button>
            <a><%= link_to "Tomspencer.co", root_path, class: "navbar-brand" %></a>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <%= link_to "About", pages_About_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Projects", pages_Projects_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Contact", pages_Contact_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
                    </li>

                    <li class="nav-item">
                        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
                    </li>

                </ul>
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  </head>

  <body>
  <%= render 'phrasing/initializer' %>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/header' %>
  <div class="container-fluid" >
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/About.html.erb
<h1>Pages#About</h1>
<p>Find me in app/views/pages/About.html.erb</p>

<%= phrase('click to edit me') %>

app/views/pages/Contact.html.erb
<h1>Pages#Contact</h1>
<p>Find me in app/views/pages/Contact.html.erb</p>

app/views/pages/Projects.html.erb
<h1>Pages#Projects</h1>
<p>Find me in app/views/pages/Projects.html.erb</p>